### ISSUE TITLE
[BUG] error: cannot find macro `asm` in this scope

### ISSUE THREAD

**Issue by nikitundrik** [LibertyOS-Development/kernel#12]
**Describe the bug**
When I tried building the kernel from the source when crates were building at the moment of compilation of lazy_static `error: cannot find macro `asm` in this scope` error appeared.

**To Reproduce**
1. Build the kernel from the instructions on the Github page. The error happened when I ran `cargo build`

**Expected behavior**
Expected that the kernel would build succesfully

**Additional information**
 - Architecture: x86_64
 - OS: Debian 11
 - Build environment: plain linux
 - QEMU version: `QEMU emulator version 5.2.0 (Debian 1:5.2+dfsg-11+deb11u1)`
 - rustc version: `rustc 1.59.0-nightly (c5ecc1570 2021-12-15)`
 - Commit hash: [here](https://github.com/LibertyOS-Development/kernel/commit/63698edac48c9be985dc149dbcc5cbd2c4a61544)

**Comment by davethiede** [comment]
Several of us are having build issues with Linux. I'm using Arch. I've found today that running a "cargo install" command will succeed. I also tried moving the rust-toolchain file out of the way to see if that made a difference but it didn't. I use the nightly toolchain by default. All of the commands were run from bootstrap.sh file except for installing rustup which is already installed on my systems.

# works
cargo install --debug --path .
cargo install --path .

# fails
cargo build
