### ISSUE TITLE
[BUG] Lock file wasn't pushed on the latest release 

### ISSUE THREAD

**Issue by Dylan-DPC** [LibertyOS-Development/kernel#17]
The Cargo.lock file wasn't pushed on the latest release (0.15.8). 

Also ensure you are running `cargo check --locked` in your CI so such mistakes can be caught at the CI level.

**Comment by danielteberian** [comment]
It's been a minute. What is the issue?

**Comment by danielteberian** [comment]
Great to see a Rust contributor here! What a surprise!

I had to take a break from this for a bit, but I am wanting to get back into it. How did you find the repo?

**Comment by Dylan-DPC** [comment]
Thanks. 
The issue is that a lock file should be pushed to git every time it is changed (even though in this case it was just a change in the version field). 

Yeah sure take your time. I found this issue while i was combing through the dependencies of `spin` which has an advisory against it, and updating it's dependents to use at least 0.9.8 version. Since you have a lockfile that should be fine, but I would still recommend doing it though at some point.

**Comment by danielteberian** [comment]
I'm logging in right now. I'll make sure to push the lockfile.

**Comment by danielteberian** [comment]
Is it fixed?

**Comment by Dylan-DPC** [comment]
it is but it won't reflect till you make a new release, this should be fine i guess, thanks for the prompt response

**Comment by danielteberian** [comment]
Okay. I can publish a new release tonight. Are you trying to work on something?

Next thing I want to do is fix the ridiculous structure of the kernel. Referencing modules should not take so long.

**Comment by Dylan-DPC** [comment]
No I am not working on anything related to this. I am going through all the crates that use `spin` and updating them as needed.

**Comment by danielteberian** [comment]
Oh, cool. How often do you do that?

Got any friends who know how to work without the standard library? ;)
