### ISSUE TITLE
Little help

### ISSUE THREAD

**Issue by berkus** [LibertyOS-Development/kernel#4]
Hi Daniel,

You asked if I could help you - sure, I can. 

Probably github discussions is not the best medium for comms, so lets figure out what we can use - Telegram, Zulip, Discord, Matrix, or forum.osdev.org forums - anything works.

**Comment by danielteberian** [comment]
I agree. Sorry for the weird way of getting in contact. Here is a Discord link to a server I threw together:

https://discord.gg/uNNSES7d


I will reply in the morning. It's past 3AM, and I have work. Thanks, again! :)

- Daniel

**Comment by berkus** [comment]
What's more weird is that I have not seen a single question yet.

**Comment by danielteberian** [comment]
I thought I asked a question. Discord has been acting strangely for a few weeks.

**Comment by danielteberian** [comment]
I wrote you a message. I am looking for help with porting some kind of standard library to run with the kernel (glibc, musl, relibc, etc.), creating a basic filesystem, and writing a simple shell.

Also, I am really annoyed that I cannot seem to get backspace working. I can type whatever I want, and it works as it should, but I cannot remove characters.
