### ISSUE TITLE
HUGE PAGES ARE UNSUPPORTED

### ISSUE THREAD

**Issue by Kepler-Br** [LibertyOS-Development/kernel#9]
Is this a successful run?
Built from [latest main commit](https://github.com/LibertyOS-Development/kernel/commit/e789e656d940c148de13f3c2aee558b0052f9c51) with 
`cargo build --release; cargo run --release`
Same without release flag.
```
LIBERTY-OS
KERNEL VERSION 0.9.7

VirtAddr(0xb8000) -> Some(PhysAddr(0xb8000))
VirtAddr(0x201008) -> Some(PhysAddr(0x401008))
VirtAddr(0x10000201a10) -> Some(PhysAddr(0x27fa10))
panicked at `[ERR] HUGE PAGES ARE UNSUPPORTED`, src/mem.rs:37:43
```
If so, please, provide expected behavior in the README.md
```
% qemu-system-x86_64 --version
QEMU emulator version 6.0.0 (Debian 1:6.0+dfsg-2expubuntu1.1)
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
```
```
% lsb_release --all
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish
```
```
% rustc --version
rustc 1.59.0-nightly (0fb1c371d 2021-12-06)
```

**Comment by danielteberian** [comment]
Hello! First, I want to thank you for bothering to check out this repository. :)

As for the error message in question, there is nothing to worry about. The message is a holdover from when paging was first being implemented in the kernel. All the messages (aside from the normal message) will be removed in the next update (either 0.9.8, or 0.10.0).

If you have any ideas, complaints, or technical issues, please open another issue or send me a message on the official Discord server.

Thank you, and God bless!
- Daniel Teberian

P.S. If you wouldn't mind, I would really appreciate it if you submitted a PR with an issue template that is similar to the one you used here. Your message was concise, informative, and did not forget anything.

**Comment by Kepler-Br** [comment]
Hello!
Where can I find a link to official Discord server? It appears that link in closed issue(aka 'Little help') is not valid anymore

**Comment by danielteberian** [comment]
https://discord.gg/3SuPAgsA
